services:
  api:
    build: ./backend
    container_name: it-asset-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/itassetmanagement
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-development-only}
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    container_name: it-asset-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
    depends_on:
      - api

  db:
    image: postgres:14
    container_name: it-asset-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=itassetmanagement
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: