version: '3.8'

services:
  api:
    build: .
    container_name: it-asset-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/itassetmanagement
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-development-only}
    volumes:
      - ./app:/app/app

  db:
    image: postgres:14
    container_name: it-asset-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=itassetmanagement
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: